#!/bin/sh

INSTANCE_ID=`curl http://169.254.169.254/latest/meta-data/instance-id`

/opt/*base/bin/membase cluster-init -c 127.0.0.1 \
    --cluster-init-username=Administrator \
    --cluster-init-password=$(INSTANCE_ID)

crontab -r

rm -f config-pkg

